export const WEEKDAYS = new Map<Number, String>();
WEEKDAYS.set(0, 'Sunday');
WEEKDAYS.set(1, 'Monday');
WEEKDAYS.set(2, 'Tuesday');
WEEKDAYS.set(3, 'Wednesday');
WEEKDAYS.set(4, 'Thursday');
WEEKDAYS.set(5, 'Friday');
WEEKDAYS.set(6, 'Saturday');

export const MONTHS = new Map<Number, String>();
MONTHS.set(0, 'January');
MONTHS.set(1, 'February');
MONTHS.set(2, 'March');
MONTHS.set(3, 'April');
MONTHS.set(4, 'May');
MONTHS.set(5, 'June');
MONTHS.set(6, 'July');
MONTHS.set(7, 'August');
MONTHS.set(8, 'September');
MONTHS.set(9, 'October');
MONTHS.set(10, 'November');
MONTHS.set(11, 'December');
