// export const WEEKDAYS = new Map<number, string>();
// WEEKDAYS.set(0, 'Sunday');
// WEEKDAYS.set(1, 'Monday');
// WEEKDAYS.set(2, 'Tuesday');
// WEEKDAYS.set(3, 'Wednesday');
// WEEKDAYS.set(4, 'Thursday');
// WEEKDAYS.set(5, 'Friday');
// WEEKDAYS.set(6, 'Saturday');

// export const MONTHS = new Map<number, string>();
// MONTHS.set(0, 'January');
// MONTHS.set(1, 'February');
// MONTHS.set(2, 'March');
// MONTHS.set(3, 'April');
// MONTHS.set(4, 'May');
// MONTHS.set(5, 'June');
// MONTHS.set(6, 'July');
// MONTHS.set(7, 'August');
// MONTHS.set(8, 'September');
// MONTHS.set(9, 'October');
// MONTHS.set(10, 'November');
// MONTHS.set(11, 'December');

export const WEEKDAYS = new Map<string, number>();
WEEKDAYS.set('Sunday', 0);
WEEKDAYS.set('Monday', 1);
WEEKDAYS.set('Tuesday', 2);
WEEKDAYS.set('Wednesday', 3);
WEEKDAYS.set('Thursday', 4);
WEEKDAYS.set('Friday', 5);
WEEKDAYS.set('Saturday', 6);

export const MONTHS = new Map<string, number>();
MONTHS.set('January', 0);
MONTHS.set('February', 1);
MONTHS.set('March', 2);
MONTHS.set('April', 3);
MONTHS.set('May', 4);
MONTHS.set('June', 5);
MONTHS.set('July', 6);
MONTHS.set('August', 7);
MONTHS.set('September', 8);
MONTHS.set('October', 9);
MONTHS.set('November', 10);
MONTHS.set('December', 11);
